app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, SelectField,StringField
from wtforms.validators import Required


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Write something about yourself', validators=[Required()])
    submit = SubmitField('Submit')


class PlaceForm(FlaskForm):
    title = StringField('Title', render_kw={"placeholder": "Title"})
    place_data = TextAreaField('New Place', )
    photo_url = StringField('Photo URL', render_kw={'placeholder': 'Photo URL'})
    location_url = StringField('Location URL', render_kw={'placeholder': 'Location URL'})
    post = SubmitField('Post place')


class CommentForm(FlaskForm):
    name = StringField('Name', validators=[Required()], render_kw={"placeholder": "Name"})
    email = StringField('Email', validators=[Required()], render_kw={"placeholder": "Email"})
    comment_data = TextAreaField('Enter Comment', validators=[Required()], render_kw={"placeholder": "Comment"})
    post = SubmitField('Post Comment')


class EmailForm(FlaskForm):
    name = StringField('First Name', validators=[Required()], render_kw={"placeholder": "First Name"})
    email = StringField('Email', validators=[Required()], render_kw={"placeholder": "Email"})
    subscribe = SubmitField('Subscribe')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, forms,main

app/main/views.py
from flask import render_template, redirect, url_for, flash, abort, request
from . import main
from ..models import User, Place, Comment
from flask_login import login_required, current_user
from .. import db, photos
from .forms import UpdateProfile, PlaceForm, CommentForm
import requests
import os
import imghdr
from datetime import datetime
from time import time, sleep
import markdown2
import sys
import random

key = os.environ.get('API_KEY')

search_url = "https://maps.googleapis.com/maps/api/place/textsearch/json"
photos_url = "https://maps.googleapis.com/maps/api/place/photo"


@main.route('/')
def index():
    """
    root page function that returns the index page and its data
    """
    title = "Welcome "

    return render_template("homepage.html", title=title)


@main.route('/homepage')
@login_required
def home():
    """
    root page function that returns the index page and its data
    """
    title = "Welcome "

    return render_template("homepage.html", title=title)


@main.route('/find_gift')
def gift():
    return render_template("gifts.html")




# @main.route('/find_gift', methods=['GET', 'POST'])
# @login_required
# def gift():
#     ans = True
#
#     while ans:
#         question = question.html
#
#         answers = random.randint(1,8)
#
#         if question == "":
#             sys.exit()
#
#
#         elif answers == 1:
#             print "It is certain"




@main.route('/user/<uname>/update', methods=['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username=uname).first()

    if user is None:
        abort(404)

    update_form = UpdateProfile()

    if update_form.validate_on_submit():
        user.bio = update_form.bio.data
        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', uname=user.username, id_user=user.id))
    title = 'Update Bio'
    return render_template('profile/update.html', form=update_form, title=title)


@main.route('/user/<uname>/update/userpic', methods=['POST'])
@login_required
def update_userpic(uname):
    user = User.query.filter_by(username=uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile', uname=uname, id_user=current_user.id))


@main.route('/place/<int:id>', methods=['GET', 'POST'])
def place(id):
    get_place = Place.query.get(id)
    get_place_comments = Comment.get_place_comments(id)

    if get_place is None:
        abort(404)

    place_format = markdown2.markdown(get_place.place_content, extras=["code-friendly", "fenced-code-blocks"])

    comment_form = CommentForm()

    if comment_form.validate_on_submit():
        user_name = comment_form.name.data
        user_email = comment_form.email.data
        user_comment = comment_form.comment_data.data

        new_comment = Comment(name=user_name, email=user_email, comment_content=user_comment,
                              date_comment=datetime.now(), place_id=id)
        new_comment.save_comment()

        return redirect(url_for('main.place', id=id))

    get_comments = Comment.get_place_comments(id)

    return render_template('place.html', place_format=place_format, get_place=get_place, title="New Gift shop",
                           comment_form=comment_form, get_comments=get_comments, comments_count=len(get_place_comments))


@main.route('/view_places', methods=['GET', 'POST'])
def view_places():
    """
    to view all places recommended

    """
    title = "Places Recommended"
    all_places = Place.get_all_places()
    if all_places:
        places = all_places
        return render_template('all_places.html', title=title, all_place=places)
    elif not all_places:
        place_message = 'No places recommended yet'
        return render_template('all_places.html', title=title, place_message=place_message)


@main.route('/create_place', methods=['GET', 'POST'])
@login_required
def create_place():
    place_form = PlaceForm()

    if place_form.validate_on_submit():
        place_title = place_form.title.data
        place = place_form.place_data.data
        url = place_form.photo_url.data
        url_second = place_form.location_url.data

        new_place = Place(title=place_title, place_content=place, date_posted=datetime.now(), photo_url=url,
                          location_url=url_second)
        new_place.save_place()

        return redirect(url_for('main.place', id=new_place.id))

    return render_template('new_place.html', title='New Place', place_form=place_form)


@main.route('/place/<int:id>/update/pic', methods=['POST'])
@login_required
def update_pic(id):
    place = Place.get_single_place(id)
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        place.place_pic = path
        # user_photo = PhotoProfile(pic_path = path,user = user)
        db.session.commit()
    return redirect(url_for('main.place', id=id))


@main.route('/place/<int:id>/<int:id_comment>/delete_comment')
@login_required
def delete_comment(id, id_comment):
    comment = Comment.get_single_comment(id, id_comment)

    db.session.delete(comment)
    db.session.commit()

    flash('Comment has been deleted')

    return redirect(url_for('main.place', id=id))


@main.route('/index/<int:id>/delete_place')
@login_required
def delete_place(id):
    place = Place.get_single_place(id)

    db.session.delete(place)
    db.session.commit()

    flash('Place has been deleted')

    return redirect(url_for('main.index'))


@main.route("/map_retrieve", methods=["GET"])
def retrieve():
    return render_template('places.html')


@main.route("/sendRequest/<string:query>")
def results(query):
    search_payload = {"key": key, "query": query}
    search_req = requests.get(search_url, params=search_payload)
    search_json = search_req.json()

    photo_id = search_json["results"][0]["photos"][0]["photo_reference"]

    photo_payload = {"key": key, "maxwidth": 500, "maxwidth": 500, "photoreference": photo_id}
    photo_request = requests.get(photos_url, params=photo_payload)

    photo_type = imghdr.what("", photo_request.content)
    photo_name = "static/" + query + "." + photo_type

    with open(photo_name, "wb") as photo:
        photo.write(photo_request.content)

    image = '<img src=' + photo_name + '>'
    return image

    return render_template('places.html', image=image)

app/main/templates/profile/profile.html
            <!-- Displaying profile photo -->
            {% if user.profile_pic_path %}
                <img src="{{url_for('static',filename = user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {% else %}
            <img src="{{url_for('static',filename = 'photos/avatar.png')}}" alt="">
            {% endif %}
            <p class="user-tag"> {{user.username|capitalize}} </p>
            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">
                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
        </div>
        <div class="col-md-8 stats">
            <!-- Displaying user bio -->
            <h3>Bio</h3>
            <hr>
            {% if user.bio %}
                <p> {{user.bio}} </p>
            {% else %}
                <p>{{user.username|capitalize}} has no bio</p>
            {% endif %}
            {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit Bio</a>
            <br>
            {% endif %}
            <br>
            <h3>Stats</h3>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope='col'></th>
                        <th scope='col'>Stats</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Apps</td>
                        <td>{{Apps_no|length}}</td>
                    </tr>
                    <tr>
                        <td>Comments</td>
                        <td>{{comments_no|length}}</td>
                    </tr>
                    <tr>
                        <td>Apps Liked</td>
                        <td>{{likes_no|length}}</td>
                    </tr>
                    <tr>
                        <td>Apps Disliked</td>
                        <td>{{dislikes_no|length}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

app/main/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      {{wtf.quick_form(form)}}
    </div>
    <div class="col-md-3"></div>
  </div>
</div>https://gist.github.com/guert/2371179
{% endblock %}